include(CheckIncludeFiles)
include(CheckSymbolExists)
check_include_files(arpa/inet.h HAVE_HEADER_ARPA_INET_H)
check_include_files(netinet/in.h HAVE_HEADER_NETINET_IN_H)
check_include_files(sys/socket.h HAVE_HEADER_SYS_SOCKET_H)
check_include_files(unistd.h HAVE_HEADER_UNISTD_H)
check_symbol_exists(socket "sys/socket.h" HAVE_FUN_SOCKET)
check_symbol_exists(bind "sys/socket.h" HAVE_FUN_BIND)
check_symbol_exists(listen "sys/socket.h" HAVE_FUN_LISTEN)
check_symbol_exists(accept "sys/socket.h" HAVE_FUN_ACCEPT)
check_symbol_exists(connect "sys/socket.h" HAVE_FUN_CONNECT)
check_symbol_exists(htons "arpa/inet.h" HAVE_FUN_HTONS)
check_symbol_exists(close "unistd.h" HAVE_FUN_CLOSE)

add_executable(tcp_echo_server server.cpp)
target_link_libraries(tcp_echo_server PRIVATE CLI11::CLI11 spdlog::spdlog)

add_executable(tcp_echo_client client.cpp)
target_link_libraries(tcp_echo_client PRIVATE CLI11::CLI11 spdlog::spdlog)
